### ISSUE TITLE
benerin code nya ya!!!

### ISSUE THREAD

**Issue by blinfoldking** [ShinyQ/Golang_TubesDAP_GajiKaryawan#1]

**Comment by blinfoldking** [comment]
https://github.com/ShinyQ/Golang_TubesDAP_GajiKaryawan/blob/2e0bcf79ceb79f71a6ee2c235e1aed91caf758bd/gaji.go#L294

pendekin ya

**Comment by blinfoldking** [comment]
https://github.com/ShinyQ/Golang_TubesDAP_GajiKaryawan/blob/2e0bcf79ceb79f71a6ee2c235e1aed91caf758bd/gaji.go#L146

ini data apaan

**Comment by ShinyQ** [comment]
Fixed https://github.com/ShinyQ/Golang_TubesDAP_GajiKaryawan/commit/6816f096ede221535b0b30b323b3508443731e6e , Terima Kasih Bang ...  @BlinfoldKing
